### ISSUE TITLE
Regression: preserving comments causes preprocessor errors

### ISSUE THREAD

**Issue by squeek502** [Vexu/arocc#1060]
test.c:
```c
#if !defined(_SAL_VERSION_SAL2) // [
foo
#endif
```

Without `--comments` (`arocc -E test.c`) everything works as expected:

```c
# 1 "test.c" 1
# 1 "<builtin>" 1
# 380 "<builtin>"
# 1 "<command line>" 1
# 1 "test.c" 2

foo
```

With `--comments` (`arocc -E --comments test.c`):

```
test.c:1:33: error: token is not a valid binary operator in a preprocessor subexpression
#if !defined(_SAL_VERSION_SAL2) // [
                                ^
```

This is a regression, not sure exactly when it happened (EDIT: likely caused by https://github.com/Vexu/arocc/pull/1038). Also reproduces with `-C` and `-CC`
