### ISSUE TITLE
Incorrect parse of function returning pointer to array

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#546]
```c
int ARRAY[2];
int (*foo(void))[2] {
    return &ARRAY;
}
```

```
./test.c:2:21: error: expected ';', found '{'
int (*foo(void))[2] {
                    ^
1 error generated.
```

**Comment by ehaas** [comment]
Introduced in 1cdf4d5380d72cd71d2a4c8dd552cd7eae4018c3
